## Numpy array and basics

In [23]:
import numpy as np

In [8]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array:", arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [12]:
py_list = [1,2,3]
print("python list multiplication: ", py_list*2)

np_arr = np.array([1,2,3]) # element-wise multiplication
print("python array multiplication: ", np_arr*2)

import time
start_time = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:",time.time() - start_time)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n numpy's array operation time:",time.time() - start)

python list multiplication:  [1, 2, 3, 1, 2, 3]
python array multiplication:  [2 4 6]

 List operation time: 0.05039644241333008

 numpy's array operation time: 0.006536960601806641


### creating array from scratch

In [22]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full_arr = np.full((2,2), 7)
print("full array: \n", full_arr)

random_arr = np.random.random((3,3))
print("random array: \n", random_arr)

sequence_arr = np.arange(0, 11, 2)
print("sequence array: \n", sequence_arr)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.24848074 0.77796777 0.30608983]
 [0.94688348 0.50933395 0.27867393]
 [0.46726243 0.07807335 0.93915686]]
sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [13]:
vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix:", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor:", tensor)

Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [22]:
arr = np.array([[1,2,3], [4,5,True]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("DataType:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
DataType: int64


### Array Reshaping

In [29]:
arr = np.arange(12)
print("arr:", arr)

reshap_arr = arr.reshape((3,4))
print("Reshaped arr:", reshap_arr)

flattened = reshap_arr.flatten()
print("Flattened arr:", flattened)

# ravel (returns view, instead of copy)
raveled = reshap_arr.ravel()
print("raveled_arr:", raveled)

# matrix transpose
transpose = reshap_arr.T
print("Reshap's Transpose Matrix:", transpose)

arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped arr: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled_arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshap's Transpose Matrix: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### What is NumPy in Python?

**NumPy** (Numerical Python) is a **powerful library** in Python used for **numerical computing**. It provides support for:

* **Arrays** (especially multi-dimensional arrays)
* **Mathematical functions**
* **Linear algebra**
* **Random number generation**

---

### Why Do We Use NumPy?

1. ✅ **Efficient array operations** (much faster than native Python lists)
2. ✅ **Support for multi-dimensional arrays** (matrices, tensors)
3. ✅ **Built-in mathematical functions** (like sum, mean, dot product)
4. ✅ **Used in data science, machine learning, simulations, etc.**

---

### Example:

```python
import numpy as np

arr = np.array([1, 2, 3])
print(arr * 2)  # Output: [2 4 6]
```

> This multiplies each element by 2 — a vectorized operation that's fast and simple.

---

In short, **NumPy is essential for fast and efficient numerical operations in Python.**

Note - When elements differ, NumPy chooses the smallest data type that can hold them all.
Python’s bool is already a subclass of int (True == 1, False == 0), so no precision is lost by converting a boolean to an integer.
