### Numpy array and basics

In [4]:
import numpy as np


In [ ]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array:", arr_2d)

### list vs numpy array

In [12]:
py_list = [1,2,3]
print("python list multiplication: ", py_list*2)

np_arr = np.array([1,2,3]) # element-wise multiplication
print("python array multiplication: ", np_arr*2)

import time
start_time = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:",time.time() - start_time)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n numpy's array operation time:",time.time() - start)

python list multiplication:  [1, 2, 3, 1, 2, 3]
python array multiplication:  [2 4 6]

 List operation time: 0.05039644241333008

 numpy's array operation time: 0.006536960601806641


### creating array from scratch

In [22]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full_arr = np.full((2,2), 7)
print("full array: \n", full_arr)

random_arr = np.random.random((3,3))
print("random array: \n", random_arr)

sequence_arr = np.arange(0, 11, 2)
print("sequence array: \n", sequence_arr)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.24848074 0.77796777 0.30608983]
 [0.94688348 0.50933395 0.27867393]
 [0.46726243 0.07807335 0.93915686]]
sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor