## Advance operation with Business examples

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Data structure: [resturant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], # Paradise Biryani
    [2, 120000, 140000, 160000, 190000], # Beijing Bites
    [3, 200000, 230000, 260000, 300000], # Pizza Hub
    [4, 180000, 210000, 240000, 270000], # Burger Point
    [5, 160000, 185000, 2050000, 230000], # Chai Point
])

print("========== Zomato Sales analysis =========")
print("\n Sales data shape:",sales_data.shape)
print("\n Sample data for 1st three resturants:", sales_data[0:3])

========== Zomato Sales analysis =========

 Sales data shape: (5, 5)

 Sample data for 1st three resturants: [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
# find total sales per year
print("Sum of sales data:", np.sum(sales_data,axis=0))
yearly_total = np.sum(sales_data[:, 1:], axis=0)
print("Yearly total:", yearly_total)

# minimum sales per resturant
min_sales = np.min(sales_data[:, 1:], axis=1)
print("minimum sales:", min_sales)

# maximum sales per year
max_sales = np.max(sales_data[:, 1:], axis=0)
print("maximum sales per year:", max_sales)

# average sales per resturant
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print("average sale:", avg_sales)

# find cumulative sum
cum_sum = np.cumsum(sales_data[:, 1:], axis=1)
print("cumulative sum:", cum_sum)

plt.figure(figsize=(8, 6))
plt.plot(np.mean(cum_sum, axis=0))
plt.title("Average cumulative sales across all resturants")
plt.xlabel("Years")
plt.ylabel("Sales")
plt.grid(True)
plt.show()

In [ ]:
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([6,7,8,9,10])

print("vector addition: ",vec1 + vec2)
print("multiplication of vectors: ", vec1 * vec2)
print("\n Dot product of vectors: ", np.dot(vec1,vec2))

get_angle = np.arccos(np.dot(vec1,vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2)))
print("Angle:", get_angle)

### vectorized operations

In [12]:
resturant_types = np.array(['briyani', 'chinese', 'pizza', 'burger', 'cafe'])
vectorized_upper = np.vectorize(str.upper)
print('vectorised upper:', vectorized_upper(resturant_types))

vectorised upper: ['BRIYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


### brodcast in numpy

In [15]:
sales_price = sales_data[:, 1:] 
print("Sales_price: ", sales_price)
montly_avg = sales_data[:, 1:] / 12
print("montly_average:",montly_avg)

Sales_price:  [[ 150000  180000  220000  250000]
 [ 120000  140000  160000  190000]
 [ 200000  230000  260000  300000]
 [ 180000  210000  240000  270000]
 [ 160000  185000 2050000  230000]]
montly_average: [[ 12500.          15000.          18333.33333333  20833.33333333]
 [ 10000.          11666.66666667  13333.33333333  15833.33333333]
 [ 16666.66666667  19166.66666667  21666.66666667  25000.        ]
 [ 15000.          17500.          20000.          22500.        ]
 [ 13333.33333333  15416.66666667 170833.33333333  19166.66666667]]


### Important Notes

- Note :- For top to bottom (column) axis should be 0 and for left to right (row), axis should be 1.